<script>
</script>

<div class="spinner-wrapper">
  <div class="loadingio-spinner-rolling-2by998twmg8">
    <div class="ldio-yzaezf3dcmj">
      <div></div>
    </div>
  </div>
</div>

<style>
  @keyframes ldio-yzaezf3dcmj {
    0% {
      transform: translate(-50%, -50%) rotate(0deg);
    }
    100% {
      transform: translate(-50%, -50%) rotate(360deg);
    }
  }
  .ldio-yzaezf3dcmj div {
    position: absolute;
    width: 120px;
    height: 120px;
    border: 20px solid #00625e;
    border-top-color: transparent;
    border-radius: 50%;
  }
  .ldio-yzaezf3dcmj div {
    animation: ldio-yzaezf3dcmj 1.25s linear infinite;
    top: 100px;
    left: 100px;
  }
  .loadingio-spinner-rolling-2by998twmg8 {
    width: 200px;
    height: 200px;
    display: inline-block;
    overflow: hidden;
    background: none;
  }
  .ldio-yzaezf3dcmj {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-yzaezf3dcmj div {
    box-sizing: content-box;
  }
  /* [ldio] generated by https://loading.io */

  .spinner-wrapper {
    width: 100%;
    height: 100%;
    display: grid;
    place-items: center; /* Centers both horizontally and vertically */
    background: lightgrey;
  }
</style>
